### ISSUE TITLE
Request for Demonstration and Local Execution Capabilities

### ISSUE THREAD

**Issue by beyhangl** [SocialComplexityLab/life2vec#3]
I'm interested in running the repository on my local machine for testing and development purposes. However, I've noticed that without sample data and model weights, it's not possible to fully execute the project locally. Are there any available resources or methods to run the repository with either sample data or some form of weights? This would greatly assist in understanding and utilizing the project more effectively.

Thank you for your assistance.

**Comment by carlomarxdk** [comment]
Hey there,
In January (likely in the second part), I'll assemble a working example with some dummy data + update the repository with code annotations 🙂

**Comment by beyhangl** [comment]
Thank you for the update. This will be very helpful for understanding and working with the repository.
