### ISSUE TITLE
Missing SOP task

### ISSUE THREAD

**Issue by turtleman99** [SocialComplexityLab/life2vec#4]
According to the README, 
```
`/tasks` contain the specification for data augmentation in MLM, SOP, etc.,
```

However, it seems missing under both `/tasks` and `/src` folders. Any information is appreciated. Thank you!

**Comment by carlomarxdk** [comment]
Thanks for the question. `SOP` task is embedded into the `MLM` task (`src/tasks/mlm.py`). 
The object `MLM` has `cls_task` method - this is the one related to the `SOP`. 

I am working on the annotated version of the code, which we will release closer to the end of January.

**Comment by turtleman99** [comment]
Thank yuo so much for the clarification. 

I'm also looking forward to the dummy data for runnning the code. Hopefully, there are also some results based on dummy code so that we are able to double check. 

Thanks again for your work!
