### ISSUE TITLE
Is there some sample data available to run this code？

### ISSUE THREAD

**Issue by b010001y** [SocialComplexityLab/life2vec#5]
I'm trying to run through your code, but you don't include the requirements.txt file in your code, which makes it extraordinarily difficult to try, and when I do run through it, there are no data samples in your code, is it only possible to get the data through the light version, and can you provide some data samples?

**Comment by carlomarxdk** [comment]
Hey there, unfortunately, we cannot provide the actual data samples; the only data available is indeed via the light version (which replicates the basic pipeline).
