### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by quantumdotsss** [SocialComplexityLab/life2vec#7]
May I how to test the model?

Thanks so much.

**Comment by carlomarxdk** [comment]
Thanks for the question! 
Unfortunately, it is not possible to test the actual pretrained model (unless you are affiliated with a Danish Company or Institution that is involved in any kind of research activity).  You can read more about the access to the data/model here: [DST Research Scheme](https://www.dst.dk/en/TilSalg/Forskningsservice/Dataadgang).
